const monthBookingData = [
  { weight: 50, isBooked: false, date: "01", booking: {} },
  { weight: 50, isBooked: false, date: "02", booking: {} },
  { weight: 50, isBooked: false, date: "03", booking: {} },
  { weight: 50, isBooked: false, date: "04", booking: {} },
  { weight: 50, isBooked: false, date: "05", booking: {} },
  { weight: 50, isBooked: false, date: "06", booking: {} },
  { weight: 50, isBooked: false, date: "07", booking: {} },
  { weight: 50, isBooked: false, date: "08", booking: {} },
  { weight: 50, isBooked: false, date: "09", booking: {} },
  { weight: 50, isBooked: false, date: "10", booking: {} },
  { weight: 50, isBooked: false, date: "11", booking: {} },
  { weight: 50, isBooked: false, date: "12", booking: {} },
  { weight: 50, isBooked: false, date: "13", booking: {} },
  { weight: 50, isBooked: false, date: "14", booking: {} },
  { weight: 50, isBooked: false, date: "15", booking: {} },
  { weight: 50, isBooked: false, date: "16", booking: {} },
  { weight: 50, isBooked: false, date: "17", booking: {} },
  { weight: 50, isBooked: false, date: "18", booking: {} },
  { weight: 50, isBooked: false, date: "19", booking: {} },
  { weight: 50, isBooked: false, date: "20", booking: {} },
  { weight: 50, isBooked: false, date: "21", booking: {} },
  { weight: 50, isBooked: false, date: "23", booking: {} },
  { weight: 50, isBooked: false, date: "24", booking: {} },
  { weight: 50, isBooked: false, date: "25", booking: {} },
  { weight: 50, isBooked: false, date: "26", booking: {} },
  { weight: 50, isBooked: false, date: "27", booking: {} },
  { weight: 50, isBooked: false, date: "28", booking: {} },
  { weight: 50, isBooked: false, date: "29", booking: {} },
  { weight: 50, isBooked: false, date: "30", booking: {} },
  { weight: 50, isBooked: false, date: "31", booking: {} },
];

module.exports = monthBookingData;
